### PR TITLE
Add aarch64 travis-ci build config

### PR DESCRIPTION
**Pull request by janaknat**
Travis-CI allows the creation of aarch64 artifacts.

Make changes in travis scripts, .travis.yml and use manylinux2014 to generate the aarch64 python wheels.

Complete log: https://travis-ci.com/github/janaknat/pycryptodome/builds/182324915
Wheel build job: https://travis-ci.com/github/janaknat/pycryptodome/jobs/380068433

### CODE REVIEW

**Comment by janaknat** [comment]
Ping! Any feedback on this PR?

**Comment by janaknat** [comment]
@Legrandin Any feedback on this PR?

**Comment by Legrandin** [comment]
Thanks. Merged.

**Comment by janaknat** [comment]
@Legrandin Thanks for accepting the PR. If I understand correctly, this repo is used as the source for both pycryptodome and pycryptodomex. I don't see any aarch64 wheels for pycryptodomex. Are there any changes to be made for those to be available?

**Comment by Legrandin** [comment]
Good point - added aarch64 wheels for `pycryptodomex` too.

**Pull request merged**
