### PR TITLE
Changed minimum mac tag length from 4 bytes to zero

### PR DESCRIPTION
**Pull request by laurolima**

### CODE REVIEW

**Comment by Legrandin** [comment]
I take that EAX didn't set any particular constraints on the tag length, but is there any practical reason to accept anything shorter than 32 bits?

**Comment by laurolima** [comment]
Yes, Google's Eddystone [specification for encrypted telemetry](https://github.com/google/eddystone/blob/master/eddystone-tlm/tlm-encrypted.md) asks for a 16 bit tag. I have taken liberty to reduce to zero, because there may be another application that uses a zero-length tag.

**Comment by Muikkunen** [comment]
Hi, this suggestion is old, but could it still be reconsidered? The company I work for also utilizes Google's Eddystone and basically we cannot utilize the library without this modification. In our case length 0 isn't required, but 2 is. The PR seems quite good, but if some more work is required, I'm ready to do that if that's needed to get this merged.

**Comment by Legrandin** [comment]
Merged with 316d1fad8c389e0bfdcd3cf299bbf893c371c3f3, but minimum MAC tag length is 2 bytes.

**Pull request closed without merging**
