### PR TITLE
md5 docs fix

### PR DESCRIPTION
**Pull request by dm248**
Fixes MD5 docs. Length extension discussion was wrong (quite hilariously in fact).

### CODE REVIEW

**Comment by Legrandin** [comment]
Length extension attacks can happen with both `MD5(m||k)` and `MD5(k||m)`, so the example in the docs is not incorrect. Or do you think otherwise?

**Comment by dm248** [comment]
The primary issue is that the original docs refer to H(m||z||p), which is trivial to compute (m, z, p are known). There is no attack in that whatsoever. You would need to involve the secret 'k' in some way. 

I did change the scheme to prefix-secret simply because it is atypical in postfix-secret schemes to care about the message part that comes after the secret. So while the forged input m||k||z||p is technically different from the original m||k, the message parser on the forgery would pick up 'm' only (assuming it does not just outright fail because the tail k||z||p does not match the expected secret 'k' exactly).

**Comment by Legrandin** [comment]
Right - I see what you mean. Thanks for clarifying.

**Comment by dm248** [comment]
yw

**Pull request merged**
