### PR TITLE
Compatibility with python 3 improved.

### PR DESCRIPTION
**Pull request by AlexanderUp**
Issues while Python3 run fixed:
1) Using time.perf_counter() instead time.time().
2) Using range() instead xrange().
3) Removing of big integer L literal.
4) Fixed encryption speed test with mode 'MODE_SIV'.

### CODE REVIEW

**Comment by Legrandin** [comment]
Issue 1 is not an issue. Can it be removed from this MR?

**Comment by AlexanderUp** [comment]
> Issue 1 is not an issue. Can it be removed from this MR?

Done.

**Comment by Legrandin** [comment]
OK, but the MR still replaces `Crypto` with `Cryptodome`, and that's not acceptable.

**Comment by AlexanderUp** [comment]
Now corrected. Sorry for misunderstanding.

**Comment by Legrandin** [comment]
Thanks, merged.

**Pull request merged**
