### PR TITLE
Build PyPy wheels only for versions 3.9 and 3.10, and not for 3.8 anymore

### PR DESCRIPTION
**Pull request by cclauss**
https://www.pypy.org/download.html

### CODE REVIEW

**Comment by gaby** [comment]
@cclauss Python3.8 is not EOL, it will gets security updates until late 2024. Source https://devguide.python.org/versions/

A lot of LTS systems use Ubuntu 20.04, which uses py3.8

**Comment by cclauss** [comment]
@gaby You are talking about CPython and I am talking about PyPy.  See the URL in the commit message.

**Comment by gaby** [comment]
> @gaby You are talking about CPython and I am talking about PyPy. See the URL in the commit message.

Ahhh! I see it

**Comment by Legrandin** [comment]
Thanks, merged as https://github.com/Legrandin/pycryptodome/commit/08bc46d937e998f01739c85e3afc84be2ae24c37

**Pull request closed without merging**
